runtime: nodejs
env: flex

env_variables:
  SQL_USER: master
  SQL_PASSWORD: '123456'
  SQL_DATABASE: happyhealth_MySQL
  INSTANCE_CONNECTION_NAME: exalted-legacy-290621:us-central1:happyhealth-test01

beta_settings:
  cloud_sql_instances: exalted-legacy-290621:us-central1:happyhealth-test01